export const expectedModels = [
  "DO_DYNAMIC_0D_ROYER_2021",
  "BIOENERGETIC_SPARUS_AURATA_BRIGOLIN_2010",
  "FEEDING_SATIETY_RULES",
  "DAILY_RATION_MODEL",
  "BPNN_MEA_FEED_INTAKE",
  "PEARSON_LSTM_ATTENTION_WQ",
  "FISH_COUNTING_MODEL",
  "FISH_SIZE_WEIGHT_ESTIMATION",
]
